### ISSUE TITLE
[DEV] 여행지 후기 게시글 작성

### ISSUE THREAD

**Issue by Hany-Kim** [KOSA-DDABONG/back-end#23]
# 화면명
여행지 후기 게시판 화면

# HTTP Protocol
POST

# URI
/post/write

# 상세 설명
게시글 작성 폼 제출 및 게시글 추가 요청

[# 참고](https://docs.google.com/spreadsheets/d/10WWR0WL7yy69751PQIpdHbZcwB60mPU_bwztd-v0BmA/edit?gid=1503761859#gid=1503761859)

┆Issue is synchronized with this [Jira Task](https://hanykim1210-1720413620514.atlassian.net/browse/KAN-32) by [Unito](https://www.unito.io)

**Comment by MG-Jang** [comment]
.
